dist: trusty
sudo: false

language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"

git:
  depth: 1

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
    - $HOME/.npm
    - node_modules

before_script:
  - node --version
  - npm --version

script:
  - npm test

matrix:
  fast_finish: true
